const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0ptckJvaTVRTzJyM0ZHTElDdnRkTzRWcytyQlZ3WTNkSEJQSjkwVUNFdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibGFVRjJJNVVZNFgyWVlVYktBRDdzTjgrblprOW14dmZXWDFYRm40Sjhsdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpRXVMTXFCVm5jVU0yQ2lMSTYwNXlrRkJSRG5ycTdqd0U0SFBCM1B3bTBZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBVFZWaU1XZ2YzeFVkQmRmbVJTMng2eUFMRHhPcStrYXV6d0VPTVJEWno0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVHbGVlMkp0RVVZUXVVQ05PTnBZVWRwdU1UMStqaVN4TExZSllCQXMzSFk9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkxLdjVvRlFhUktnNG9URVpyb1E1bHNOUG5WQUFoOUFzaEhsY0crbjUxamM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0ZXaHpyd1ZnQ0FwY2FWTk4xdCtWVXFiYzVreTFxa203eUNBdGkya2RGRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiajA2OVl1eWhlaFdocHBRb1Y0SmZ3eFJHbi9wbkRmeWVPeE5rOURHcFEydz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ilhia2tCN1lLVjlvb1dRRXZtMG05emtmakN6Q1JrNzFrU0QyQmlMU3pxY2xNTlVVc3JGbXNXZzlsemZWVlVlT3NBU1p2Sm8rYXM2am9rRVdEVHNtYmpBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjE2LCJhZHZTZWNyZXRLZXkiOiJFb2lHY2JVZSsrRnRzbVZPQVFzUjFGMlBNelAwVWhTWFlGREZyNWtmYVZnPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjkxNzkwMjQ5MjEwOEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBQzlBMkUwNEUxNEZDQTg1ODAxMzZEQjIzNTk4NERFQSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQyOTkwNjk2fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5MTc5MDI0OTIxMDhAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMUE5MTMxQjZEOTZDOUU0Q0E4RjRGRTA0QkE1MDM0MjkifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0Mjk5MDY5Nn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiZy1janMyUXpTN1dXWTl0YW5XU2RSZyIsInBob25lSWQiOiIxMDdlNDE4MC03OThlLTRjOWUtOGU0ZS04ZTAyMjQ4Nzc5MWIiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRE9qWCs1d1lwU3FwaDZRbWZnT2tEeVJyL3FVPSJ9LCJyZWdpc3RlcmVkIjpmYWxzZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5ZjZXd2dhQUJnaHlQai85TTBXdjlXK0gzOGs9In0sInJlZ2lzdHJhdGlvbiI6e30sImFjY291bnQiOnsiZGV0YWlscyI6IkNMRGRpMTBRMTlxUHZ3WVlBU0FBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJMcXpFdTZ1clVnMG9vRC9VSERmZTVCNUl6a1lhVkgwS2ozd3g5N1NsRFZBPSIsImFjY291bnRTaWduYXR1cmUiOiJFNFlpQjE5NnRESk0xNmFNaTVZSzk3NUQzcHVveENHQnpVN2w0a29OSUk1S0g1dy9Ea0ZZUjc5QjUzOFNlS2FaNE94aUo5WXMxSnE0ekZTNE15VXNEZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiYmduY3hkWjJuN3JLNEV2ZnFyd1l4cUNGdi9lN3FpeVp4SnhIV3VlbXV3bitPUTBwUVdUOG9MUzB5dG96MWdHMVJYVURqdklDQ25BY3ludHJXQTZKZ1E9PSJ9LCJtZSI6eyJpZCI6IjkxNzkwMjQ5MjEwODoyMEBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLwnZCo8J2Qp/CdkJ4g8J2QnfCdkJrwnZCyIn0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjkxNzkwMjQ5MjEwODoyMEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJTNnN4THVycTFJTktLQS8xQnczM3VRZVNNNUdHbFI5Q285OE1mZTBwUTFRIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzQyOTkwNjkyLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU5kKyJ9",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "917902492108",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
